"""Increase emoji column length

Revision ID: 03c197fe7769
Revises: c4c6bf1ee088
Create Date: 2026-05-13 18:16:10.921343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c197fe7769'
down_revision = 'c4c6bf1ee088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
