services:
  backend:
    build: ./calendar-project
    ports:
      - "5000:5000"
    volumes:
      - ./calendar-project:/app

  frontend:
    build: ./calendar-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./calendar-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: calendar_db
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
